name: Generate Stats Images

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "1 0 * * 1-5"
  workflow_dispatch:

jobs:
  run-on-ubuntu:
    name: Try on ubuntu-latest
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      failed: ${{ steps.check-failure.outcome }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt

      - name: Generate images and cache
        run: |
          python3 generate_images.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCLUDED: ${{ secrets.EXCLUDED }}
          EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
          COUNT_STATS_FROM_FORKS: ${{ secrets.COUNT_STATS_FROM_FORKS }}

      - name: Commit results
        run: |
          git config --global user.name "github-stats[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add generated/ contribution_cache.json
          git commit -m 'temp commit' || echo
          git checkout output 2>/dev/null || git checkout --orphan output && git rm -rf . && git checkout main -- generated/ contribution_cache.json
          git commit -m 'Update generated files and cache' || echo
          git push origin output -f

      - name: Mark success/failure
        id: check-failure
        run: exit 0
        if: ${{ failure() }}

  run-on-self-hosted:
    name: Fallback on self-hosted
    runs-on: self-hosted
    needs: run-on-ubuntu
    if: ${{ needs.run-on-ubuntu.result == 'failure' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt

      - name: Generate images and cache
        run: |
          python3 generate_images.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCLUDED: ${{ secrets.EXCLUDED }}
          EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
          COUNT_STATS_FROM_FORKS: ${{ secrets.COUNT_STATS_FROM_FORKS }}

      - name: Commit results
        run: |
          git config --global user.name "github-stats[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add generated/ contribution_cache.json
          git commit -m 'temp commit' || echo
          git checkout output 2>/dev/null || git checkout --orphan output && git rm -rf . && git checkout main -- generated/ contribution_cache.json
          git commit -m 'Update generated files and cache' || echo
          git push origin output -f
